select 
ORDER_ITEM_SEQ,
PROMPT_SEQ,
DISP_SEQ,
DFLT_RESPONSE,
MAND_FL,
MIN_RESPONSE,
MAX_RESPONSE,
NAME_MODIFIER,
IS_CLINICALLY_RELEVANT,
PROMPT_TEXT,
DFLT_UNIT,
CURRENT_VALUE,
CURRENT_UNIT,
RECOMMENDED_VAL_SEQ,
ALLOWED_VAL_SEQ,
ALLOWED_UNIT_SEQ,
LIMIT_TO_AVAILABLE,
VISIBLE_FL,
READ_ONLY_HEO,
DISPLAY_ON_NEW_LINE

from O_ITEM_PROMPT oip  

where oip.order_item_seq = :pid
order by oip.disp_seq asc